#!/usr/bin/env bash

require 'env-vars/chef'

export PATHS_ORGANIZATION_BERKSHELF_HOME="${PATHS_ORGANIZATION_HOME}/.berkshelf"
export BERKSHELF_PATH="${PATHS_ORGANIZATION_BERKSHELF_HOME}"

export BERKSHELF_CONFIG="${PEMBA_CHEF_HOME}/berkshelf-config.json"

export PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_WORKSPACE_BERKSFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_WORKSPACE_HOME}/Berksfile"
export BERKSFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_WORKSPACE_BERKSFILE}"

export PEMBA_CHEF_BERKSFILE="${PEMBA_CHEF_HOME}/Berksfile"