#!/usr/bin/env bash

require 'env-vars/ruby'

export BUNDLER_VERSION=1.12.5

export BUNDLER_BIN="${GEM_HOME}/bin/bundle"

export PATHS_PROJECT_WORKSPACE_SETTINGS_BUNDLE_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/bundle"
export PATHS_PROJECT_WORKSPACE_SETTINGS_BUNDLE_GEMFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_BUNDLE_HOME}/Gemfile"
export BUNDLE_GEMFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_BUNDLE_GEMFILE}"

export BUNDLE_BIN_PATH="${GEM_HOME}/gems/bundler-${BUNDLER_VERSION}/bin/bundle"

export PATHS_PROJECT_BUNDLE_INSTALL_FLAG_FILE="${GEM_HOME}/.${PROJECT_NAME}-bundle-install-flag"

export PEMBA_BUNDLE_HOME="${PEMBA_PATHS_HOME}/bundle"
export PEMBA_BUNDLE_GEMFILE="${PEMBA_BUNDLE_HOME}/Gemfile"




