#!/usr/bin/env bash

export ECOSYSTEM_CHEF_HOME="${ECOSYSTEM_PATHS_HOME}/chef"

export PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/chef"
export PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_HOME}/cookbook"
export PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_WORKSPACE_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_COOKBOOK_HOME}/workspace"
export PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_DATA_BAGS_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_CHEF_HOME}/data_bags"

export PATHS_PROJECT_DEPLOY_CHEF_HOME="${PATHS_PROJECT_DEPLOY_HOME}/chef"
export PATHS_PROJECT_DEPLOY_CHEF_COOKBOOK_HOME="${PATHS_PROJECT_DEPLOY_CHEF_HOME}/cookbook"
export PATHS_PROJECT_DEPLOY_CHEF_DATA_BAGS_HOME="${PATHS_PROJECT_DEPLOY_CHEF_HOME}/data_bags"
