#!/usr/bin/env bash

require 'env-vars/python'

export PIPENV_VERSION=1.12.5

export PIPENV_BIN="${GEM_HOME}/bin/pipenv"

export PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/pipenv"
export PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_GEMFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_HOME}/Gemfile"
export PIPENV_GEMFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_GEMFILE}"

export PIPENV_BIN_PATH="${GEM_HOME}/gems/pipenv-${PIPENV_VERSION}/bin/pipenv"

export PATHS_PROJECT_PIPENV_INSTALL_FLAG_FILE="${GEM_HOME}/.${PROJECT_NAME}-pipenv-install-flag"

export PEMBA_PIPENV_HOME="${PEMBA_PATHS_HOME}/pipenv"
export PEMBA_PIPENV_GEMFILE="${PEMBA_PIPENV_HOME}/Gemfile"
