#!/usr/bin/env bash

require 'env-vars/python'

export PIPENV_VERSION=1.12.5

export PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/pipenv"
export PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_PIPFILE="${PATHS_PROJECT_WORKSPACE_SETTINGS_PIPENV_HOME}/Pipfile"

export PATHS_PROJECT_PIPENV_INSTALL_FLAG_FILE="${PATHS_TMP_DIR}/.${PROJECT_NAME}-pipenv-install-flag"

export PEMBA_PIPENV_HOME="${PEMBA_PATHS_HOME}/pipenv"
export PEMBA_PIPENV_PIPFILE="${PEMBA_PIPENV_HOME}/Pipfile"
