#!/usr/bin/env bash

export RAKE_SYSTEM="${PEMBA_PATHS_HOME}/rake"
export PEMBA_RAKE_PATH="${RAKE_SYSTEM}"
export PEMBA_PATHS_RAKE_HOME="${PEMBA_PATHS_HOME}/rake"
export PEMBA_PATHS_RAKE_LIB_HOME="${PEMBA_PATHS_RAKE_HOME}/lib"
export PEMBA_PATHS_RAKE_LIB_TEMPLATES_HOME="${PEMBA_PATHS_RAKE_LIB_HOME}/templates"

export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/rake"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_HOME}/lib"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_TASKS_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/tasks"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_CLASSES_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/classes"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_TEMPLATES_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/templates"
