#!/usr/bin/env bash

export RAKE_SYSTEM="${ECOSYSTEM_PATHS_HOME}/rake"
export ECOSYSTEM_RAKE_PATH="${RAKE_SYSTEM}"
export ECOSYSTEM_PATHS_RAKE_HOME="${ECOSYSTEM_PATHS_HOME}/rake"
export ECOSYSTEM_PATHS_RAKE_LIB_HOME="${ECOSYSTEM_PATHS_RAKE_HOME}/lib"
export ECOSYSTEM_PATHS_RAKE_LIB_TEMPLATES_HOME="${ECOSYSTEM_PATHS_RAKE_LIB_HOME}/templates"

export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_HOME}/rake"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_HOME}/lib"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_TASKS_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/tasks"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_CLASSES_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/classes"
export PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_TEMPLATES_HOME="${PATHS_PROJECT_WORKSPACE_SETTINGS_RAKE_LIB_HOME}/templates"
